name: CI Space Invaders

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  Quality-and-Tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Space-Invaders/SpaceInvaders-e664e935fa518d7edea6a0db6d779da46edd0a90
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Space-Invaders/SpaceInvaders-e664e935fa518d7edea6a0db6d779da46edd0a90/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Linter (Google Style)
        run: npm run lint

      - name: Security Audit (npm audit)
        run: npm audit --audit-level=moderate || true

      - name: Unit Tests (Jest)
        run: npm test

      - name: Functional Tests (Playwright)
        run: |
          npx playwright install --with-deps
          npx playwright test